### ISSUE TITLE
Extra features BRAIN STORM 

### ISSUE THREAD

**Issue by mslaursen** [kea-semester-1/best-bank-as#45]

**Comment by Moshizzl3** [comment]
Suggestions:
- Customer chat
- Email

**Comment by Moshizzl3** [comment]
More suggetions:
- credit
- Interest (Both for loans, and if u have money in the bank - also for credit if that is implemented)
- Automatic logoff if you have been afk for 5 mins (this is a very common feature)
- Ratelimiting on transfer endpoints
- audit log, see here for example: https://github.com/kea-semester-1/Semester-Project/blob/main/rpg_api/db/postgres/migrations/versions/2023-12-14-17-28_f24e163963f2.py
